import type { Metadata } from 'next'
import cn from 'clsx'
import { headers } from 'next/headers'
import { Inter, Cairo, Open_Sans, Roboto_Mono } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import { SearchParamsProvider } from '@/shared/ui/'
import '../_styles/globals.css'

const inter = Inter({
	variable: '--font-inter',
	weight: ['400', '500', '600'],
	display: 'swap',
	subsets: ['latin', 'cyrillic'],
})

const cairo = Cairo({
	variable: '--font-cairo',
	weight: ['400', '500', '600'],
	display: 'swap',
	subsets: ['latin'], // Cairo не поддерживает кириллицу
})

const openSans = Open_Sans({
	variable: '--font-open-sans',
	weight: ['400', '500', '600', '700'],
	display: 'swap',
	subsets: ['latin', 'cyrillic'],
})

const robotoMono = Roboto_Mono({
	variable: '--font-roboto-mono',
	weight: ['400', '500', '600', '700'],
	display: 'swap',
	subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
	title: 'AitiGuru Test',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const headersList = await headers()
	const searchParams = headersList.get('x-search-params') ?? ''

	return (
		<html lang="ru">
			<body className={cn(inter.className, cairo.variable, openSans.variable, robotoMono.variable, 'antialiased')}>
				<SearchParamsProvider searchParams={searchParams}>{children}</SearchParamsProvider>
				<ToastContainer position="top-center" theme="colored" />
			</body>
		</html>
	)
}
